/** Contractor project sectors (distinct from sub-contractor trade filters). */
export const contractorProjectTypesSeed: { slug: string; nameEn: string; nameTr: string }[] = [
  { slug: "residential", nameEn: "Residential", nameTr: "Konut" },
  { slug: "commercial", nameEn: "Commercial", nameTr: "Ticari" },
  { slug: "industrial", nameEn: "Industrial", nameTr: "Endüstriyel" },
  { slug: "institutional", nameEn: "Institutional", nameTr: "Kurumsal" },
  { slug: "healthcare", nameEn: "Healthcare", nameTr: "Sağlık" },
  { slug: "education", nameEn: "Education", nameTr: "Eğitim" },
  { slug: "hospitality", nameEn: "Hospitality", nameTr: "Konaklama" },
  { slug: "retail", nameEn: "Retail", nameTr: "Perakende" },
  { slug: "sports-recreation", nameEn: "Sports & recreation", nameTr: "Spor ve rekreasyon" },
  { slug: "cultural-religious", nameEn: "Cultural / religious", nameTr: "Kültürel / dini" },
  { slug: "roads-highways", nameEn: "Roads & highways", nameTr: "Karayolu" },
  { slug: "bridges-viaducts", nameEn: "Bridges & viaducts", nameTr: "Köprü ve viyadük" },
  { slug: "tunnels", nameEn: "Tunnels", nameTr: "Tünel" },
  { slug: "railways-metros", nameEn: "Railways & metros", nameTr: "Demiryolu ve metro" },
  { slug: "airports", nameEn: "Airports", nameTr: "Havalimanı" },
  { slug: "ports-marine", nameEn: "Ports & marine", nameTr: "Liman ve deniz" },
  { slug: "dams-water", nameEn: "Dams & water structures", nameTr: "Baraj ve su yapıları" },
  { slug: "water-sewer-drainage", nameEn: "Water / sewer / drainage", nameTr: "Su, kanalizasyon, drenaj" },
  { slug: "energy", nameEn: "Energy", nameTr: "Enerji" },
  { slug: "oil-gas", nameEn: "Oil & gas", nameTr: "Petrol ve gaz" },
  { slug: "utilities", nameEn: "Utilities", nameTr: "Altyapı hizmetleri" },
  { slug: "environmental", nameEn: "Environmental", nameTr: "Çevre" },
  { slug: "renovation-fitout", nameEn: "Renovation / fit-out", nameTr: "Yenileme / iç mekan" },
  { slug: "restoration-retrofit", nameEn: "Restoration / retrofit", nameTr: "Restorasyon / güçlendirme" },
  { slug: "demolition", nameEn: "Demolition", nameTr: "Yıkım" },
  { slug: "mixed-use", nameEn: "Mixed-use", nameTr: "Karma kullanım" },
  { slug: "data-centers", nameEn: "Data centers", nameTr: "Veri merkezleri" },
  { slug: "warehousing-logistics", nameEn: "Warehousing & logistics", nameTr: "Depo ve lojistik" },
  { slug: "land-development", nameEn: "Land development", nameTr: "Arazi geliştirme" }
];
