/** Top-level sub-contractor filter groups (registration picks one). */
export const subcontractorMainCategoriesSeed: { slug: string; nameEn: string; nameTr: string }[] = [
  { slug: "siteworks", nameEn: "Siteworks", nameTr: "Saha işleri" },
  { slug: "concrete", nameEn: "Concrete", nameTr: "Beton" },
  { slug: "structural-steel", nameEn: "Structural steel", nameTr: "Çelik karkas" },
  { slug: "carpentry", nameEn: "Carpentry", nameTr: "Marangozluk" },
  { slug: "masonry", nameEn: "Masonry", nameTr: "Duvarcılık" },
  { slug: "facade-cladding", nameEn: "Façade / cladding", nameTr: "Cephe / kaplama" },
  { slug: "roofing", nameEn: "Roofing", nameTr: "Çatı" },
  { slug: "waterproofing", nameEn: "Waterproofing", nameTr: "Su yalıtımı" },
  { slug: "insulation", nameEn: "Insulation", nameTr: "İzolasyon" },
  { slug: "plumbing", nameEn: "Plumbing", nameTr: "Tesisat" },
  { slug: "hvac", nameEn: "HVAC", nameTr: "HVAC" },
  { slug: "fire-protection", nameEn: "Fire protection", nameTr: "Yangın güvenliği" },
  { slug: "electrical", nameEn: "Electrical", nameTr: "Elektrik" },
  { slug: "low-current", nameEn: "Low-current / weak current", nameTr: "Zayıf akım" },
  { slug: "drywall-ceilings", nameEn: "Drywall / ceilings", nameTr: "Alçıpan / asma tavan" },
  { slug: "painting", nameEn: "Painting", nameTr: "Boya" },
  { slug: "flooring", nameEn: "Flooring", nameTr: "Zemin" },
  { slug: "joinery", nameEn: "Joinery", nameTr: "Doğrama" },
  { slug: "glass-glazing", nameEn: "Glass / glazing", nameTr: "Cam" },
  { slug: "metalworks", nameEn: "Metalworks", nameTr: "Metal işleri" },
  { slug: "elevator-escalator", nameEn: "Elevator / escalator", nameTr: "Asansör / yürüyen merdiven" },
  { slug: "landscaping", nameEn: "Landscaping", nameTr: "Peyzaj" },
  { slug: "road-paving", nameEn: "Road / paving", nameTr: "Yol / kaplama" },
  { slug: "industrial-systems", nameEn: "Industrial systems", nameTr: "Endüstriyel sistemler" },
  { slug: "fit-out", nameEn: "Fit-out", nameTr: "İç mekan uygulama" },
  { slug: "restoration", nameEn: "Restoration", nameTr: "Restorasyon" },
  { slug: "testing-commissioning", nameEn: "Testing / commissioning", nameTr: "Test / devreye alma" },
  { slug: "temporary-scaffolding", nameEn: "Temporary works / scaffolding", nameTr: "İskele / geçici işler" },
  { slug: "cleaning-waste", nameEn: "Cleaning / waste", nameTr: "Temizlik / atık" }
];
